<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.apache.maven</groupId>
    <artifactId>native</artifactId>
    <version>4.1.0-SNAPSHOT</version>
  </parent>
  <artifactId>prebuilt-feature</artifactId>
  <packaging>jar</packaging>
  <properties>
    <exec.mainClass>org.apache.maven.org.apache.maven.nmvn.features.features.PrebuiltFeature</exec.mainClass>
    <!-- SanitizeRealmJars is using API from version 25 -->
    <minimalJavaBuildVersion>25</minimalJavaBuildVersion>
    <maven.compiler.release>${minimalJavaBuildVersion}</maven.compiler.release>
  </properties>
  <dependencies>
    <dependency>
      <groupId>org.apache.maven</groupId>
      <artifactId>maven-api-annotations</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.maven</groupId>
      <artifactId>maven-cli</artifactId>
    </dependency>
    <dependency>
      <groupId>org.graalvm.sdk</groupId>
      <artifactId>graal-sdk</artifactId>
      <version>25.1.3</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>com.google.inject</groupId>
      <artifactId>guice</artifactId>
      <classifier>classes</classifier>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.eclipse.sisu</groupId>
      <artifactId>org.eclipse.sisu.inject</artifactId>
      <scope>provided</scope>
    </dependency>
  </dependencies>
</project>
